baseurl = "http://www.ryotaniinomi.com"
languageCode = "ja"
title = "r21nomi.log"
MetaDataFormat = "yaml"
googleAnalytics = "UA-81203103-1"

[params]
    description = "nomi"
    author = "Ryota Niinomi"

[params.inc]
    title = "r21nomi.log"
    subtitle = "Art & Tech log"
    cover_image = "blog-cover.jpg"
    logo = "logo.gif"
    # company = "CyberAgent,inc"
    url = "http://www.ryotaniinomi.com"
    github = "r21nomi"
    twitter = "r21nomi"
    about_link = "http://www.ryotaniinomi.com/about"
    # product_link = "http://www.ryotaniinomi.com"
    # tagline = ""

[params.inc.disqus]
    shortname =  false

[params.inc.sharing]
    twitter = true
    facebook = true
    gplus = false
